owner: MADA-Mando-de-Datos
repo: MADA_status

sites:
  - name: Odoo
    url: https://0gerardo0.engineer/web/login
    headers:
      - "x-mada-monitor-auth: $MADA_WAF"
  - name: Nextcloud (TEST ALERT)
    url: https://cloud.0gerardo0.engineer/error_forzado_para_test
    headers:
      - "x-mada-monitor-auth: $MADA_WAF"
status-website:
  cname: status.0gerardo0.engineer
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado del Sistema MADA
  introTitle: "Monitoreo en tiempo real de nuestra infraestructura."
  introMessage: "Aquí puedes verificar el estado de los servidores de Odoo y Nextcloud."
  introText: "Sistemas operativos 24/7."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
